# Generated by Django 3.0.7 on 2020-06-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='书籍类别表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=50, unique=True)),
                ('描述', models.TextField(blank=True)),
                ('图片', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name_plural': '书籍类别表',
                'db_table': '书籍类别表',
            },
        ),
        migrations.CreateModel(
            name='书籍列表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=30, unique=True)),
                ('ISBN', models.CharField(max_length=15, unique=True)),
                ('作者', models.CharField(max_length=30)),
                ('价格', models.DecimalField(decimal_places=2, max_digits=10)),
                ('剩余数量', models.IntegerField(default=0)),
                ('出版社', models.CharField(max_length=30)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('描述', models.TextField(blank=True)),
                ('图片', models.ImageField(blank=True, upload_to='category')),
                ('类别', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.书籍类别表')),
            ],
            options={
                'verbose_name_plural': '书籍列表',
                'db_table': '书籍列表',
                'ordering': ('-创建时间',),
            },
        ),
    ]
