# Generated by Django 3.0.7 on 2020-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=30, unique=True)),
                ('ISBN', models.CharField(max_length=15, unique=True)),
                ('BookAuthor', models.CharField(max_length=30)),
                ('BookPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BookRemainNum', models.IntegerField(default=0)),
                ('BookPress', models.CharField(max_length=30)),
                ('BookCategory', models.CharField(max_length=30)),
                ('Photo', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'db_table': 'Books',
                'ordering': ('ISBN',),
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberAccount', models.CharField(max_length=10, unique=True)),
                ('MemberPassword', models.CharField(max_length=10)),
                ('MemberName', models.CharField(max_length=30)),
                ('MemberAdress', models.CharField(max_length=30)),
                ('MemberPhone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['MemberAccount'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='书籍列表',
        ),
        migrations.DeleteModel(
            name='书籍类别表',
        ),
    ]
