# Generated by Django 3.0.7 on 2020-06-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20200608_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='BookCategory',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookPress',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterModelTable(
            name='members',
            table='Members',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=20, unique=True)),
                ('OrderNum', models.IntegerField(default=1)),
                ('OrderTime', models.DateTimeField(auto_now_add=True)),
                ('OrderState', models.CharField(max_length=10)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Books')),
                ('MemberAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Members')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Orders',
                'ordering': ['OrderTime'],
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CartNum', models.IntegerField(default=1)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Books')),
                ('MemberAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Members')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'Carts',
                'ordering': ['MemberAccount'],
            },
        ),
    ]
